server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # Si alguien entra a una URL profunda, devuelve el index.html para que React maneje la ruta
    location / {
        try_files $uri $uri/ /index.html;
    }
}
