ALTER TABLE patients
  ADD COLUMN IF NOT EXISTS authorized_at DATE;

ALTER TABLE patients
  ADD COLUMN IF NOT EXISTS authorization_expires_at DATE;

CREATE TABLE IF NOT EXISTS patient_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id TEXT NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  apply_treatments BOOLEAN NOT NULL DEFAULT FALSE,
  applied_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE patient_requests
  ADD COLUMN IF NOT EXISTS apply_treatments BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE patient_requests
  ADD COLUMN IF NOT EXISTS applied_at TIMESTAMPTZ;

CREATE INDEX IF NOT EXISTS idx_patient_requests_patient
  ON patient_requests(patient_id);

CREATE INDEX IF NOT EXISTS idx_patient_requests_dates
  ON patient_requests(start_date, end_date);

CREATE TABLE IF NOT EXISTS patient_request_treatments (
  request_id BIGINT NOT NULL REFERENCES patient_requests(id) ON DELETE CASCADE,
  treatment_id BIGINT NOT NULL REFERENCES treatments(id) ON DELETE CASCADE,
  PRIMARY KEY (request_id, treatment_id)
);

UPDATE patients
SET authorized_at = CURRENT_DATE
WHERE COALESCE(is_active, FALSE) = TRUE
  AND authorized_at IS NULL;
